### ISSUE TITLE
add css   @media for Tablets, Smartphones 

### ISSUE THREAD

**Issue by Knm24** [singularity-autumn-2023/team3-skilled-elearning-landing-page#4]
/* ##Device = Desktops */
  @media (min-width: 48rem) {
    
  }

  /* ##Device = Tablets, Ipads (portrait) */
  @media (max-width: 48rem) {
  
  }

  /* ##Device = Most of the Smartphones Mobiles */
  @media   (max-width: 21.4375rem) { 
  
 }

**Comment by Annurkenova** [comment]
+

**Comment by Annurkenova** [comment]
ok

**Comment by Knm24** [comment]
/* ##Device = Desktops */
https://github.com/media (min-width: 768px) {

/* ##Device = Tablets, Ipads (portrait) */
https://github.com/media only screen and (min-width: 460px) and (max-width: 767px) {

/* ##Device = Most of the Smartphones Mobiles */
https://github.com/media (max-width: 460px) {
